### ISSUE TITLE
🚀 Feature: allow specifying multiple --ownership values with commas

### ISSUE THREAD

**Issue by ljharb** [JoshuaKGoldberg/tidelift-me-up#10]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/tidelift-me-up/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

The docs say the default is `author,publisher` but when i try to provide `--ownership=author,publisher,maintainer` I get:
```sh
Error: Unknown --ownership: author,maintainer,publisher (must be one of: author, maintainer, publisher)
    at assertValidOwnership (file://$HOME/.npm/_npx/3874edfee03e1fcc/node_modules/tidelift-me-up/lib/assertValidOwnership.js:6:23)
    at tideliftMeUpCli (file://$HOME/.npm/_npx/3874edfee03e1fcc/node_modules/tidelift-me-up/lib/tideliftMeUpCli.js:20:5)
    at async file://$HOME/.npm/_npx/3874edfee03e1fcc/node_modules/tidelift-me-up/lib/cli.js:3:1

```

### Actual

see above

**Comment by JoshuaKGoldberg** [comment]
The correct syntax (right now) is `--ownership author --ownership publisher --ownership maintainer`:

https://github.com/JoshuaKGoldberg/tidelift-me-up/blob/4b5163b56c2f7df7a621fe35d53df3a052c9ea84/README.md#L58-L60

I suppose we could `ownership.flatMap(raw => raw.split(","))` internally to allow for comma-separated values too - accepting PRs as a convenience. Thanks for filing!

**Comment by ljharb** [comment]
ahhh that makes sense, thanks.
