### ISSUE TITLE
🚀 Feature: `--json`

### ISSUE THREAD

**Issue by ljharb** [JoshuaKGoldberg/tidelift-me-up#12]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/tidelift-me-up/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I'd like to pass `--json` and get the output on stdout in JSON format (as is typical, anything that's not valid json should be outputted on stderr)

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @ljharb for ideas
