### ISSUE TITLE
hide lifted packages

### ISSUE THREAD

**Issue by ljharb** [JoshuaKGoldberg/tidelift-me-up#218]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/tidelift-me-up/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I'd like to only show packages that aren't already lifted.

**Comment by JoshuaKGoldberg** [comment]
Makes sense. I think we could see a `--status` option added to filter on `"available"` or `"lifted"`.

**Comment by ljharb** [comment]
and "all" i guess, as the default.
