### ISSUE TITLE
📝 Documentation: Mention what Tidelift does 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/tidelift-me-up#47]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/tidelift-me-up/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

[Tidelift](https://tidelift.com) is a great thing but not everyone knows what it does. The docs here should mention it's a service that lets companies put money into a fund that gets distributed amongst their open source dependencies. Those dependencies need to show they do some good practices around maintenance & security in order to receive funds. It's a really good idea IMO - win win!

### Additional Info

Thanks @matthew-dean for pointing out that this is never mentioned anywhere!

Sibling issue to https://github.com/JoshuaKGoldberg/tidelift-me-up-site/issues/18.

**Comment by NilanchalaPanda** [comment]
Hey Joshua, just went through your Github and was stunned by the consistency that you have kept in your work.
I am 3rd year student pursuing Bachelor's degree in Information Technology. Currently I am exploring and trying to contribute to tech domain through Open Source Contributions; and starting with something simple would be a great. So can you assign the documentation correction to me? Thank you for considering my request.

**Comment by JoshuaKGoldberg** [comment]
❤️ thanks so much @NilanchalaPanda! I'm excited you're exploring open source, that's awesome. I actually just wrote a blog post about contributing to my repositories such as this one: https://www.joshuakgoldberg.com/blog/contributing-to-a-create-typescript-app-repository. It might be useful for you.

I don't use any kind of assignment / issue-taking situation for repos (https://github.com/JoshuaKGoldberg/tidelift-me-up/blob/b95f34eab9b176ca3c33b363c2066f5dae6f05da/.github/CONTRIBUTING.md#issue-claiming). So if you want to send a pull request, go ahead!

**Comment by NilanchalaPanda** [comment]
You're welcome! Thank you for sharing your blog post about contributing to repositories, I will definitely check it out. I will go ahead and send a pull request if I have any changes or improvements do suggest. 

Once again, thank you for your guidance and open approach to contributions!
